name: Build
on:
  push:
    branches: [main, dev]

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: "revenge-mod/builds"
          path: "builds"
          token: ${{ secrets.BUILDS_PUSH_TOKEN }}
          ref: ${{ github.ref_name }}

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: |
          bun i

      - name: Build
        run: bun run build

      - name: Push builds
        run: |
          rm $GITHUB_WORKSPACE/builds/* || true
          cp -r dist/* $GITHUB_WORKSPACE/builds || true
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push

      # NOTE: Temporarily disabled, enable if needed
      - name: Purge CDN cache
        if: ${{ false }}
        run: |
          curl https://purge.jsdelivr.net/gh/revenge-mod/builds

